### PR TITLE
PILOT-1451: Allow dot within folder name for uploading

### PR DESCRIPTION
**Pull request by hugoantunes**
## Summary

replace . with / in parent_path

## JIRA Issues

https://indocconsortium.atlassian.net/browse/PILOT-1685

## Type of Change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update
- [x] Refactor or reformatting

## Testing

Are there any new or updated tests to validate the changes?

- [ ] Yes
- [x] No

## Test Directions

(Additional instructions for how to run tests or validate functionality if not covered by unit tests)

### CODE REVIEW

**Comment by gregmccoy** [comment]
@hugoantunes I think some spots were missed which I found while testing for the BFF updates. Can you update these? 
https://github.com/PilotDataPlatform/metadata/blob/PILOT-1451/app/routers/v1/items/crud_items.py#L229
https://github.com/PilotDataPlatform/metadata/blob/PILOT-1451/app/routers/v1/items/crud_items.py#L238
https://github.com/PilotDataPlatform/metadata/blob/PILOT-1451/app/routers/v1/items/crud_items.py#L98-L102

**Comment by hugoantunes** [comment]
@gregmccoy, I had to keep the `.` between the folders in the Postgres because of the format of the [LTREE](https://www.postgresql.org/docs/current/ltree.html). But the dots in the folder names are being encoded so it not considered separators.

**Comment by gregmccoy** [comment]
I see makes sense, sorry to bug you

**Comment by hugoantunes** [comment]
@gregmccoy all good!

**Review by andricDu — APPROVED** [review]

**Pull request merged**
